In [1]:
import numpy as np

In [3]:
# Tạo mảng
a = np.array([8,19,18])

# In mảng
print(a)

# In ra 1 phần tử
element = a[1]
print(element)

[ 8 19 18]
19


In [4]:
# Tạo mảng 2 chiều
matrix = np.array([[19,8,18], [9,24,1], [7, 10, 8]])
print("Matrix:")
print(matrix)

# In một phần tử
element = matrix[1, 2]
print(element)

Matrix:
[[19  8 18]
 [ 9 24  1]
 [ 7 10  8]]
1


In [8]:
# Cách tạo mảng
# Tạo mảng toàn là số 0
a = np.zeros(7)
print(a)

# Tạo mảng toàn là số 1
a = np.ones(7)
print(a)

# Tạo mảng
a = np.empty(7)
print(a)

# Tạo mảng từ 0 đến 99
a = np.arange(100)
print(a)

# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 10, num=5)
print(a)


# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
a

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [9]:
# Thêm, xóa, sắp xếp mảng

# Tạo mảng ban đầu
arr = np.array([3, 1, 2, 4, 5])
print(arr)

[3 1 2 4 5]


In [10]:
# Sắp xếp
arr = np.sort(arr)
print(arr)

[1 2 3 4 5]


In [11]:
# Sắp xếp ngược
arr = np.sort(arr)[::-1]
print(arr)

[5 4 3 2 1]


In [12]:
# Thêm phần tử vào mảng
arr = np.append(arr, 18)
print(arr)

[ 5  4  3  2  1 18]


In [13]:
# Xóa đi một ví trí nào đó trong mảng
arr = np.delete(arr, 2)
print(arr)

[ 5  4  2  1 18]


In [17]:
# Tạo một mảng 2 chiều
arr = np.array([[7, 1, 24],[19, 9, 3],[18, 10, 8]])

sap_xep_theo_hang = np.sort(arr, axis=1) # tăng dần
print(sap_xep_theo_hang)

sap_xep_theo_cot = np.sort(arr, axis=0) # tăng dần
print(sap_xep_theo_cot)

[[ 1  7 24]
 [ 3  9 19]
 [ 8 10 18]]
[[ 7  1  3]
 [18  9  8]
 [19 10 24]]


In [19]:
# Tạo một mảng 2 chiều
arr = np.array([[7, 1, 24],[19, 9, 3],[18, 10, 8]])

sap_xep_theo_hang = -np.sort(-arr, axis=1) # giảm dần
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0) # giảm dần
print(sap_xep_theo_cot)

[[24  7  1]
 [19  9  3]
 [18 10  8]]
[[19 10 24]
 [18  9  8]
 [ 7  1  3]]


In [20]:
# Tạo một mảng 2D
arr = np.array([[19, 18, 8], [9, 24, 1]])

# Sử dụng các thuộc tính để lấy thông tin về mảng
so_chieu = arr.ndim  
kich_thuoc = arr.size 
hinh_dang = arr.shape  

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [21]:
# Chuyển đổi kiểu dữ liệu
arr = np.array([18, 9, 19, 8, 3])
arr_float = arr.astype(float)
print(arr_float)

[18.  9. 19.  8.  3.]


In [23]:
# Thay đổi hình dạng của mảng
arr = np.array([18, 9, 19, 8, 24, 1])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[18  9 19]
 [ 8 24  1]]
[[18  9]
 [19  8]
 [24  1]]


In [24]:
reshaped_arr = reshaped_arr.flatten() # Chuyển thành mảng 1 chiều
print(reshaped_arr)

[18  9 19  8 24  1]


In [27]:
# Cắt lát mảng
arr = np.array([18, 9, 19, 8, 3])

sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr) 

sub_arr = arr[:-1]  
print(sub_arr)

sub_arr = arr[-2:]  
print(sub_arr)

[ 9 19  8]
[18  9 19  8]
[8 3]


In [28]:
# Chuyển vị mảng
arr = np.array([[19, 8, 18], [9, 24, 1]])
print(arr)
# Để chuyển vị mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[19  8 18]
 [ 9 24  1]]
[[19  9]
 [ 8 24]
 [18  1]]


In [29]:
# Nối mảng
arr1 = np.array([19, 8, 18])
arr2 = np.array([9, 24, 1])
arr = np.concatenate((arr1, arr2))
print(arr)

[19  8 18  9 24  1]


In [30]:
# II. Hàm tính tổng (Sum)
# - Hàm numpy.sum() cho phép tính tổng các phần tử trong mảng.
arr = np.array([19, 8, 18, 9, 24])
total = np.sum(arr)
print("Tổng của mảng arr:", total)

# III. Hàm tính trung bình (Mean)
# - Hàm numpy.mean() tính giá trị trung bình của các phần tử trong mảng.
average = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average)

# IV. Hàm tìm giá trị lớn nhất và nhỏ nhất (Max và Min)
# - Hàm numpy.max() và numpy.min() dùng để tìm giá trị lớn nhất và nhỏ nhất trong mảng.
max_value = np.max(arr)
min_value = np.min(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

# V. Hàm tính độ lệch chuẩn (Standard Deviation)
# - Hàm numpy.std() tính độ lệch chuẩn của mảng, đo lường mức độ phân tán của dữ liệu.
std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

# VI. Hàm tính phương sai (Variance)
# - Hàm numpy.var() tính phương sai của mảng, đo lường mức độ biến thiên của dữ liệu.
variance = np.var(arr)
print("Phương sai của mảng arr:", variance)

# VII. Hàm tính tổng tích chập (Dot Product)
# - Hàm numpy.dot() tính tổng tích chập của hai mảng (vector).
arr1 = np.array([19, 8, 18])
arr2 = np.array([9, 24, 1])
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của arr1 và arr2:", dot_product)

Tổng của mảng arr: 78
Giá trị trung bình của mảng arr: 15.6
Giá trị lớn nhất trong mảng arr: 24
Giá trị nhỏ nhất trong mảng arr: 8
Độ lệch chuẩn của mảng arr: 6.151422599691879
Phương sai của mảng arr: 37.839999999999996
Tổng tích chập của arr1 và arr2: 381
